src/br/com/escolamusica/controller/AlunoController.java
package br.com.escolamusica.controller;

import java.io.IOException;
import java.util.List;
import java.util.Map;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import org.apache.commons.io.IOUtils;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

import br.com.escolamusica.dao.AlunoDAO;
import br.com.escolamusica.modelo.Aluno;
import br.com.escolamusica.modelo.Estado;

@ManagedBean
@SessionScoped
public class AlunoController {

	private Aluno aluno = new Aluno();
	private Aluno alunoExclusao;
	private List<Aluno> alunos = AlunoDAO.listar();

	public String salvar() {
		AlunoDAO.salvar(aluno);
		aluno = new Aluno();
		alunos = AlunoDAO.listar();
		return "ListaAlunos?faces-redirect=true";
	}

	public String editar(Aluno aluno) {
		this.aluno = aluno;
		return "CadastroAluno?faces-redirect=true";
	}

	public String cancelar() {
		aluno = new Aluno();
		return "ListaAlunos?faces-redirect=true";
	}

	public void prepararExclusao(Aluno aluno) {
		alunoExclusao = aluno;
	}

	public void excluir() {
		AlunoDAO.excluir(alunoExclusao);
		alunos = AlunoDAO.listar();
	}

	public Estado[] getEstados() {
		return Estado.values();
	}

	public void enviarFoto(FileUploadEvent event) throws IOException {
		byte[] foto = IOUtils.toByteArray(event.getFile().getInputstream());
		aluno.setFoto(foto);
	}

	public StreamedContent getImagemAluno() {
		Map<String, String> mapaParametros = FacesContext.getCurrentInstance()
				.getExternalContext().getRequestParameterMap();
		String idAlunoStr = mapaParametros.get("idAluno");
		if(idAlunoStr != null){
			Long idAluno = new Long(idAlunoStr);
			Aluno alunoBanco = AlunoDAO.obterPorId(idAluno);
			return alunoBanco.getImagem();
		} 
		
		return new DefaultStreamedContent();
		
	}

	public Aluno getAluno() {
		return aluno;
	}

	public void setAluno(Aluno aluno) {
		this.aluno = aluno;
	}

	public List<Aluno> getAlunos() {
		return alunos;
	}

	public void setAlunos(List<Aluno> alunos) {
		this.alunos = alunos;
	}

}

src/br/com/escolamusica/controller/CursoController.java
package br.com.escolamusica.controller;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import br.com.escolamusica.dao.CursoDAO;
import br.com.escolamusica.modelo.Curso;
import br.com.escolamusica.modelo.TipoCurso;

@ManagedBean
@SessionScoped
public class CursoController {
	
	private Curso curso = new Curso();
	private List<Curso> listaCursos = CursoDAO.listar();
	private Curso cursoExclusao;

	public String salvarCurso(){
		System.out.println("Salvando curso");
		CursoDAO.salvar(curso);
		listaCursos = CursoDAO.listar();
		curso = new Curso();
		return "ListaCursos?faces-redirect=true";
	}
	
	public String editar(Curso curso){
		this.curso = curso;
		return "CadastroCurso?faces-redirect=true";
	}
	
	public void prepararExclusao(Curso curso){
		cursoExclusao = curso;
	}
	
	public void excluir(){
		CursoDAO.excluir(cursoExclusao);
		listaCursos = CursoDAO.listar();
	}
	
	public String cancelar(){
		this.curso = new Curso();
		return "ListaCursos?faces-redirect=true"; 
	}
	
	public TipoCurso[] getTiposCurso(){
		return TipoCurso.values();
	}
	
	

	public Curso getCurso() {
		return curso;
	}

	public void setCurso(Curso curso) {
		this.curso = curso;
	}

	public List<Curso> getListaCursos() {
		return listaCursos;
	}

	public void setListaCursos(List<Curso> listaCursos) {
		this.listaCursos = listaCursos;
	}

	
}

WebContent/paginas/alunos/CadastroAluno.xhtml
<!DOCTYPE html >

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>Cadastro de Alunos</title>
	<link type="text/css" rel="stylesheet" href="../../css/style.css"></link>
</h:head>
<h:body>
	<p:panel header="Cadastro de Alunos" style="width:50%">
		<h:form id="cadastro-aluno-form">
			<p:growl />
			<p:panel header="Dados pessoais">
				<h:panelGrid columns="2" cellpadding="5">
					<h:outputLabel value="Foto:"/>
					<h:panelGrid columns="2" id="grid-update">
						<p:fileUpload auto="true" label="Selecione uma foto"
							allowTypes="/(\.|\/)(jpe?g|png)$/"
							invalidFileMessage="Formato de arquivo inválido"
							dragDropSupport="true"
							update="grid-update" sizeLimit="1000000"
							fileUploadListener="#{alunoController.enviarFoto}"/>
						
						<h:panelGroup id="imagem-aluno">
							<p:graphicImage value="#{alunoController.aluno.imagem}"
							rendered="#{alunoController.aluno.foto != null}"
							width="100px;" height="100px;"
							/>
						</h:panelGroup>
					</h:panelGrid>
					<h:outputLabel value="Nome:"/>
					<p:inputText value="#{alunoController.aluno.nome}"/>
					<h:outputLabel value="Cpf:"/>
					<p:inputMask mask="999.999.999-99" value="#{alunoController.aluno.cpf}"/>
					<h:outputLabel value="Email:"/>
					<p:inputText value="#{alunoController.aluno.email}"
						placeholder="EX:email@teste.com.br"/>
					<h:outputLabel value="Telefone:"/>
					<p:inputMask mask="(99)9?99999999" value="#{alunoController.aluno.telefone}"/>
					<h:outputLabel value="Data Nasc."/>
					<p:calendar pattern="dd/mm/yyyy" mask="99/99/9999" showOn="button"
						navigator="true" yearRange="1950:2018"
						value="#{alunoController.aluno.dataNascimento}"/>
					<h:outputLabel value="Ativo"/>
					<p:selectBooleanCheckbox value="#{alunoController.aluno.ativo}"/>
				</h:panelGrid>
			</p:panel>
			<p:panel header="Dados de endereço">
				<h:panelGrid columns="2" cellpadding="5">
					<h:outputLabel value="Endereço:"/>
					<p:inputText value="#{alunoController.aluno.endereco.logradouro}"/>
					<h:outputLabel value="Número:"/>
					<p:inputText value="#{alunoController.aluno.endereco.numero}"/>
					<h:outputLabel value="Bairro:"/>
					<p:inputText value="#{alunoController.aluno.endereco.bairro}"/>
					<h:outputLabel value="Cidade:"/>
					<p:inputText value="#{alunoController.aluno.endereco.cidade}"/>
					<h:outputLabel value="Estado:"/>
					
					<p:selectOneMenu value="#{alunoController.aluno.endereco.estado}">
						<f:selectItem itemLabel="Selecione" itemValue="#{null}"/>
						<f:selectItems value="#{alunoController.estados}" var="estado"
							itemLabel="#{estado}" itemValue="#{estado}"/>
					</p:selectOneMenu>
					
					<h:outputLabel value="CEP:"/>
					<p:inputMask mask="99999-999" value="#{alunoController.aluno.endereco.cep}"/>
				</h:panelGrid>	
					
			</p:panel>
			<br/>
			<p:commandButton value="Salvar" action="#{alunoController.salvar}"
				update="@form"/>
			<p:commandButton value="Cancelar" action="#{alunoController.cancelar}"
				process="@this"/>	
		</h:form>
	</p:panel>
</h:body>
</html>

WebContent/paginas/alunos/ListaAlunos.xhtml
<!DOCTYPE html >

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>Lista de Alunos</title>
	<link type="text/css" rel="stylesheet" href="../../css/style.css"></link>
</h:head>
<h:body>
	<p:button value="Novo Aluno" outcome="CadastroAluno" icon="novo-icon"/>
	<h:form>
		<p:dataTable widgetVar="tabelaAlunos" value="#{alunoController.alunos}" var="aluno"
			style="margin-top:10px;width:90%" paginator="true" rows="5"
			paginatorPosition="bottom" rowsPerPageTemplate="2, 3, 5, 10"
			>
			<p:column headerText="Foto" width="15%">
				<p:graphicImage value="#{alunoController.imagemAluno}"
					width="80px;" height="80px;">
					<f:param name="idAluno" value="#{aluno.id}"/>
				</p:graphicImage>
			</p:column>
			<p:column headerText="Nome" width="20%"
				filterBy="#{aluno.nome}" filterMatchMode="contains"
				sortBy="#{aluno.nome}">
				<h:outputText value="#{aluno.nome}" />
			</p:column>
			<p:column headerText="Cpf" width="15%">
				<h:outputText value="#{aluno.cpf}" />
			</p:column>
			<p:column headerText="Email"
				width="18%">
				<h:outputText value="#{aluno.email}"/>
			</p:column>
			<p:column headerText="Telefone"
				width="18%">
				<h:outputText value="#{aluno.telefone}"/>
			</p:column>
			<p:column headerText="Cidade"
				width="18%">
				<h:outputText value="#{aluno.endereco.cidade} - #{aluno.endereco.estado}"/>
			</p:column>
			<p:column style="text-align:center" width="15%">
				<p:commandButton icon="fa fa-edit"
					action="#{alunoController.editar(aluno)}" />
				<p:commandButton icon="fa fa-trash" style="margin-left:8px;"
					action="#{alunoController.prepararExclusao(aluno)}"
					oncomplete="PF('confirmarExclusaoAlunoDialog').show()" />
			</p:column>
		</p:dataTable>

		<p:confirmDialog widgetVar="confirmarExclusaoAlunoDialog"
			message="Deseja realmente excluir este aluno?">
			<p:commandButton value="Sim" action="#{alunoController.excluir}"
				update="@form"
				oncomplete="PF('confirmarExclusaoAlunoDialog').hide()" />
			<p:commandButton value="Não"
				oncomplete="PF('confirmarExclusaoAlunoDialog').hide()" />
		</p:confirmDialog>
	</h:form>
</h:body>
</html>

WebContent/paginas/cursos/CadastroCurso.xhtml
<!DOCTYPE html >

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>Cadastro de Cursos</title>
	<link type="text/css" rel="stylesheet" href="../../css/style.css"></link>
</h:head>
<h:body>
	<p:panel header="Cadastro de Cursos" style="width:50%">
		<h:form id="cadastro-curso-form">
			<p:messages />
			<p:growl autoUpdate="true" life="6000" />
			<h:panelGrid columns="2" cellpadding="5">
				<h:outputLabel value="Nome" />
				<p:inputText value="#{cursoController.curso.nome}" required="true"
					requiredMessage="Informe o campo nome" />
				<h:outputLabel value="Descrição" />
				<h:panelGrid>
					<p:inputTextarea cols="40" rows="3" counter="display"
						maxlength="255" counterTemplate="{0} caracteres restantes"
						required="true" requiredMessage="Informe a descrição"
						validatorMessage="A descrição deve ter ao menos 10 caracteres"
						value="#{cursoController.curso.descricao}">
						<f:validateLength minimum="10" />
					</p:inputTextarea>

					<h:outputText id="display" />
				</h:panelGrid>
				<h:outputLabel value="Tipo" />
				<p:selectOneMenu value="#{cursoController.curso.tipo}"
					required="true" requiredMessage="Selecione o tipo">
					<f:selectItem itemValue="#{null}" itemLabel="::Selecione::" />
					<f:selectItems value="#{cursoController.tiposCurso}" var="tipo"
						itemValue="#{tipo}" itemLabel="#{tipo.label}" />
				</p:selectOneMenu>
				<h:outputLabel value="Duração" />
				<p:inputText value="#{cursoController.curso.duracao}" />
				<h:outputLabel value="Data de Criação" />
				<p:calendar value="#{cursoController.curso.dataCriacao}"
					pattern="dd/MM/yyyy" mask="99/99/9999" navigator="true"
					yearRange="1950:2017" maxdate="11/11/2017" showOn="button" />
			</h:panelGrid>
			<h:panelGrid columns="2" cellpadding="8">
				<p:commandButton value="Salvar" icon="salvar-icon"
					action="#{cursoController.salvarCurso}" />
				<p:commandButton value="Cancelar" icon="cancelar-icon"
					action="#{cursoController.cancelar}" process="@this" />
			</h:panelGrid>
		</h:form>
	</p:panel>
</h:body>
</html>

WebContent/paginas/cursos/ListaCursos.xhtml
<!DOCTYPE html >

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>Lista de Cursos</title>
	<link type="text/css" rel="stylesheet" href="../../css/style.css"></link>
</h:head>
<h:body>
	<p:button value="Novo Curso" outcome="CadastroCurso" icon="novo-icon"/>
	<h:form>
		<p:dataTable widgetVar="tabelaCursos" value="#{cursoController.listaCursos}" var="curso"
			style="margin-top:10px;width:70%" paginator="true" rows="5"
			paginatorPosition="bottom" rowsPerPageTemplate="2, 3, 5, 10"
			>
			<p:column headerText="Nome" 
				filterBy="#{curso.nome}" filterMatchMode="contains"
				sortBy="#{curso.nome}">
				<h:outputText value="#{curso.nome}" />
			</p:column>
			<p:column headerText="Tipo" filterBy="#{curso.tipo}" width="20%">
				<f:facet name="filter">
					<p:selectOneMenu onchange="PF('tabelaCursos').filter()">
						<f:selectItem itemValue="#{null}" itemLabel="Selecione"/>
						
						<f:selectItems value="#{cursoController.tiposCurso}"
							var="tipo" itemValue="#{tipo}" 
							itemLabel="#{tipo.label}"/>
							
					</p:selectOneMenu>
				</f:facet>
				<h:outputText value="#{curso.tipo.label}" />
			</p:column>
			<p:column headerText="Duração" width="15%">
				<h:outputText value="#{curso.duracao}" />
			</p:column>
			<p:column headerText="Data Criação" style="text-align:center"
				sortBy="#{curso.dataCriacao}" width="18%">
				<h:outputText value="#{curso.dataCriacao}">
					<f:convertDateTime pattern="dd/MM/yyyy" locale="pt_BR" />
				</h:outputText>
			</p:column>
			<p:column style="text-align:center" width="15%">
				<p:commandButton icon="fa fa-edit"
					action="#{cursoController.editar(curso)}" />
				<p:commandButton icon="fa fa-trash" style="margin-left:8px;"
					action="#{cursoController.prepararExclusao(curso)}"
					oncomplete="PF('confirmarExclusaoCursoDialog').show()" />
			</p:column>
		</p:dataTable>

		<p:confirmDialog widgetVar="confirmarExclusaoCursoDialog"
			message="Deseja realmente excluir este curso?">
			<p:commandButton value="Sim" action="#{cursoController.excluir}"
				update="@form"
				oncomplete="PF('confirmarExclusaoCursoDialog').hide()" />
			<p:commandButton value="Não"
				oncomplete="PF('confirmarExclusaoCursoDialog').hide()" />
		</p:confirmDialog>
	</h:form>
</h:body>
</html>